server:
  port: 80

spring:
  application:
    name: cloud-order-feign-server

eureka:
  client:
    # 表示是否将自己注册进EurekaService 默认是true
    register-with-eureka: true
    # 是否从EurekaService 抓取自己的注册信息， 默认为true 单个节点无所谓 ， 集群必须设置为true 才能配合ribbon 使用负载均衡
    fetch-registry: true
    service-url:
      #      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/

# 下面的配置会没有提示，如果你能直接的记得那么就记得 ， 如果不可以就他妈的想办法记
# 设置feign客户端超时时间（openfeign默认支持ribbon）
ribbon:
  # 值得是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ReadTimeout: 5000
  # 指的是简历连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000

logging:
  level:
    # feign 日志以什么级别监控那个接口
    com.rtrs.service.PaymentFeignService: debug



