server:
  port: 8002

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://10.10.1.43:3306/nacos_config?characterEncoding=utf8&connectTimeout=10000&socketTimeout=30000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&&serverTimezone=UTC
    username: root
    password: 123456


eureka:
  client:
    # 表示是否将自己注册进EurekaService 默认是true
    register-with-eureka: true
    # 是否从EurekaService 抓取自己的注册信息， 默认为true 单个节点无所谓 ， 集群必须设置为true 才能配合tibbon 使用负载均衡
    fetch-registry: true
    service-url:
      #defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: payment8002
    prefer-ip-address: true # 访问网络可以现实ip地址
    # eureka 客户端向服务端发送心跳得时间间隔， 单位为秒（默认是30s）
    lease-renewal-interval-in-seconds: 1
    # eureka 服务端在接收到最后一次心跳后等待时间上限，单位为秒（默认90s），超时将剔除服务
    lease-expiration-duration-in-seconds: 2

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.rtrs.entities
