server:
  port: 89

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 10.10.1.92
      #server-addr: localhost:8848 # this is localhost request

service-url:
  nacos-user-service: http://nacos-payment-provider